### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by phenric** [peterfreeman/ngx-dropzone#32]
Hi,

When I drop a picture inside the ngx-dropzone component, this error occurs

> TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

I'm using ngx-dropzone 2.0.3 with Angular 8 and I followed the example wrote by @peterfreeman (https://stackblitz.com/edit/ngx-dropzone)

home.component.html:
`
   <ngx-dropzone (change)="onSelect($event)">
                <ngx-dropzone-label>Drop it, baby!</ngx-dropzone-label>
                <ngx-dropzone-preview ngProjectAs="ngx-dropzone-preview" *ngFor="let f of files" [removable]="true" (removed)="onRemove(f)">
                    <ngx-dropzone-label>{{ f.name }}</ngx-dropzone-label>
                </ngx-dropzone-preview>
            </ngx-dropzone>
`

home.component.ts:
`
onSelect(event) {
      console.log(event);
      this.files.push( ...event.addedFiles);
  }
`
`
  onRemove(event) {
      console.log(event);
      this.files.splice(this.files.indexOf(event), 1);
  }`

What did I wrong ?
Thank you for the help you'll provide me

**Comment by peterfreeman** [comment]
Hi,

did you declare the `files` variable correctly in your HomeComponent?
`const files: File[] = [];`

Happy coding! 🤓

**Comment by phenric** [comment]
Hi,

Thank you for your rapid answer.
Yes, I declared the files variable inside the HomeComponent.
According to the console, the error occurs on this line 

> this.files.push( ...event.addedFiles);

Happy coding to you too !
Thank you for your open source work and your time !

**Comment by phenric** [comment]
OK ! I've found how to fix the issue. This is not the best one but it works, for now.
I noticed the function _onSelect_ is called two times, exactly like in your example. However and I don't know why, the second call in my app creates an error as mentioned before. So I've just created a condition and it works.

`onSelect(event) {
        if (event.addedFiles)
            this.files.push( ...event.addedFiles);
    }`

**Comment by peterfreeman** [comment]
Fixed in v2.0.4.

**Comment by elvissibetyu** [comment]
> Fixed in v2.0.4.

Hi, 
I am still having the same issue as https://github.com/peterfreeman/ngx-dropzone/issues/32#issue-488760257 
I tried the fix that is mentioned above and it is still not working. Same error.

**Comment by phenric** [comment]
@elvissibetyu,
Could you share some of your codes? Or create a [Stackblitz](https://stackblitz.com/) for reproducing?
Which version do you use?

**Comment by elvissibetyu** [comment]
@phenric I have fixed the issue, thank you. 
Instead of using pushing 2 times to the array as in the demo I only pushed when I am uploading. Thank you for your reply.

**Comment by phenric** [comment]
@elvissibetyu Happy to read it's solved
